[project]
name = 'model-upgrade-dao'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.model-upgrade-dao]
path = 'contracts/model-upgrade-dao.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = false
